version: '3.7'

services:
  currency-exchange:
    image: elkaelcr7/mmv3-currency-exchange-service:1.0-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network

networks:
  currency-network:
